### PR TITLE
init release commit

### PR DESCRIPTION
**Pull request by yeshaokai**
- full code release of amadeusGPT source code and streamlit app

### CODE REVIEW

**Comment by yeshaokai** [comment]
The pytest failure is caused by API key not in the secret variable. I probably do not have access to setting the secret variable in this repo.

**Comment by MMathisLab** [comment]
@yeshaokai can you confirm the errors are still due to a missing openAI key; it, to me, seems a code error: missing `amadeusgpt.modules` -- but I might have updated something inadvertently in my testing...

**Comment by MMathisLab** [comment]
failing due to 
```bash
=========================== short test summary info ============================
ERROR tests/test_EPM.py - FileNotFoundError: [Errno 2] No such file or directory: '/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/amadeusgpt/interface.txt'
ERROR tests/test_MABE.py - FileNotFoundError: [Errno 2] No such file or directory: '/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/amadeusgpt/interface.txt'
ERROR tests/test_MausHaus.py - FileNotFoundError: [Errno 2] No such file or directory: '/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/amadeusgpt/interface.txt'
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
========================= 1 warning, 3 errors in 5.56s =========================

**Review by MMathisLab — APPROVED** [review]
Please see convo to resolve failing test in another PR; 
- The test is failing due to poor `import *` 
- and then interface.txt not being read properly. 
- also need to decide if pinning torch, cebra, etc is needed for some OS.

**Pull request merged**
